name: build and test

on:
  push:

jobs:
  build-n-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v3
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --logger "trx;LogFileName=test-results.trx" --no-restore
#      run: dotnet test --logger "trx;LogFileName=test-results.trx" --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --output .\coverage-reports\
    - name: Test Report
      ses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Tests report stuff         # Name of the check run which will be created
        path: TestApi.Tests/TestResults/test-results.trx    # Path to test results
        reporter: dotnet-trx  
