name: run sanity [tests]

on:
  workflow_run:
    workflows:
      - build and test
    types:
      - completed
jobs:
  build-n-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2