name: run sanity [tests]

on:
  workflow_run:
    workflows:
      - build and test
    types:
      - completed
jobs:
  build-n-test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: bob
        env:
          GITHUB_CONTEXT: ${{ github.event.workflow_run.head_branch }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
        
        